name: Scan Docker Images

on:
  push: null
  pull_request: null

jobs:
  scan-images:
    name: Scan Docker Images for Vulnerabilities
    runs-on: ubuntu-latest

    steps:
      # Étape pour vérifier le code source
      - name: Checkout Code
        uses: actions/checkout@v3

      # Étape pour configurer Trivy
      - name: Setup Trivy
        uses: aquasecurity/trivy-action@v0.29.0
        with:
          version: latest

      # Scanner l'image Node.js
      - name: Scan Node.js Base Image
        run: |
          echo "Scanning Node.js image: node:18.20-slim"
          trivy image --severity CRITICAL,HIGH node:18.20-slim

      # Scanner l'image Nginx
      - name: Scan Nginx Base Image
        run: |
          echo "Scanning Nginx image: nginx:1.24-alpine-slim"
          trivy image --severity CRITICAL,HIGH nginx:1.24-alpine-slim
