name: Scan Docker Images

on:
  push: null
  pull_request: null

jobs:
  scan-images:
    name: Scan Docker Images for Vulnerabilities
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      # To report GitHub Actions status checks
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          format: 'table'
          exit-code: '1'
          output: 'table.txt'
